# Generated by Django 4.2.29 on 2026-03-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2BClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('contract_status', models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed'), ('Active', 'Active'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Documents Pending', 'Documents Pending'), ('Processing', 'Processing'), ('Visa Applied', 'Visa Applied'), ('Approved', 'Approved'), ('Ticket Booked', 'Ticket Booked'), ('Boarded', 'Boarded'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='New', max_length=30)),
                ('medical_status', models.CharField(choices=[('Pending', 'Pending'), ('Fit', 'Fit'), ('Unfit', 'Unfit'), ('Awaiting Report', 'Awaiting Report'), ('Done', 'Done')], default='Pending', max_length=30)),
                ('visa_status', models.CharField(choices=[('Not Applied', 'Not Applied'), ('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='Not Applied', max_length=30)),
                ('ticket_status', models.CharField(choices=[('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Not Booked', max_length=30)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resume_status', models.CharField(choices=[('Not Received', 'Not Received'), ('Received', 'Received'), ('Uploaded', 'Uploaded')], default='Not Received', max_length=30)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('passport_copy_status', models.CharField(choices=[('Not Received', 'Not Received'), ('Soft Copy', 'Soft Copy'), ('Original', 'Original'), ('Both', 'Both')], default='Not Received', max_length=30)),
                ('passport_copy_file', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('offer_letter_status', models.CharField(choices=[('Not Received', 'Not Received'), ('Received', 'Received'), ('Signed', 'Signed'), ('Sent to Candidate', 'Sent to Candidate')], default='Not Received', max_length=30)),
                ('offer_letter_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('candidate_type', models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Repeat', 'Repeat')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('GPay', 'GPay'), ('Cheque', 'Cheque'), ('DD', 'DD')], default='Cash', max_length=30)),
                ('purpose', models.CharField(choices=[('Registration Fee', 'Registration Fee'), ('Visa Fee', 'Visa Fee'), ('Air Ticket', 'Air Ticket'), ('Documentation', 'Documentation'), ('Training Fee', 'Training Fee'), ('Miscellaneous', 'Miscellaneous')], default='Registration Fee', max_length=50)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.candidate')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LegalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_signed', models.BooleanField(default=False)),
                ('sop_shared', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('refund_eligible', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('cancellation_status', models.CharField(choices=[('No', 'No'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='No', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_records', to='crm.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(choices=[('Immigration', 'Immigration'), ('Documentation', 'Documentation'), ('Training', 'Training'), ('Visit Visa', 'Visit Visa'), ('Accommodation', 'Accommodation'), ('B2B', 'B2B')], default='Immigration', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.candidate')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Passport', 'Passport'), ('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Degree Certificate', 'Degree Certificate'), ('School Certificate', 'School Certificate'), ('Experience Letter', 'Experience Letter'), ('Medical Certificate', 'Medical Certificate'), ('Other', 'Other')], max_length=50)),
                ('is_original', models.BooleanField(default=False)),
                ('is_attested', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('with_company', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.candidate')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='CourierEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Inward', 'Inward'), ('Outward', 'Outward')], max_length=10)),
                ('from_person', models.CharField(blank=True, max_length=200)),
                ('to_person', models.CharField(blank=True, max_length=200)),
                ('courier_company', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contents', models.CharField(blank=True, max_length=200)),
                ('handled_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='crm.candidate')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('job_category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('Documents Pending', 'Documents Pending'), ('Processing', 'Processing'), ('Visa Applied', 'Visa Applied'), ('Approved', 'Approved'), ('Ticket Booked', 'Ticket Booked'), ('Boarded', 'Boarded'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='New', max_length=30)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('boarding_date', models.DateField(blank=True, null=True)),
                ('package_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
